"""Basic Tables

Revision ID: 400d987e033e
Revises:
Create Date: 2026-04-23 23:26:52.700709

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "400d987e033e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "base_ingredient",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "recipe",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "component",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("base_ingredient_id", sa.Integer(), nullable=True),
        sa.Column("sub_recipe_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.DECIMAL(), nullable=True),
        sa.Column("quantity_unit", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["base_ingredient_id"], ["base_ingredient.id"], name="foreign_ingredient_id"
        ),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipe.id"], name="foreign_recipe_id"),
        sa.ForeignKeyConstraint(
            ["sub_recipe_id"], ["recipe.id"], name="foreign_sub_recipe_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "recipe_id",
            "base_ingredient_id",
            "sub_recipe_id",
            name="unique_recipe_component",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("component")
    op.drop_table("recipe")
    op.drop_table("base_ingredient")
    # ### end Alembic commands ###
