"""Fix Unique Component

Revision ID: cf2eef9b38cd
Revises: 400d987e033e
Create Date: 2026-04-26 16:29:52.730953

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cf2eef9b38cd"
down_revision: Union[str, Sequence[str], None] = "400d987e033e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("component") as batch_op:
        batch_op.drop_constraint(op.f("unique_recipe_component"), type_="unique")
        batch_op.create_unique_constraint(
            "unique_recipe_ingredient", ["recipe_id", "base_ingredient_id"]
        )
        batch_op.create_unique_constraint(
            "unique_recipe_sub_recipe", ["recipe_id", "sub_recipe_id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("component") as batch_op:
        batch_op.drop_constraint("unique_recipe_sub_recipe", type_="unique")
        batch_op.drop_constraint("unique_recipe_ingredient", type_="unique")
        batch_op.create_unique_constraint(
            op.f("unique_recipe_component"),
            ["recipe_id", "base_ingredient_id", "sub_recipe_id"],
        )
    # ### end Alembic commands ###
