"""Category

Revision ID: eeaeb405f819
Revises: cf2eef9b38cd
Create Date: 2026-04-26 17:33:51.286489

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "eeaeb405f819"
down_revision: Union[str, Sequence[str], None] = "cf2eef9b38cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "base_ingredient_category",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    with op.batch_alter_table("base_ingredient") as batch_op:
        batch_op.add_column(
            sa.Column("base_ingredient_category_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            "foreign_ingredient_category_id",
            "base_ingredient_category",
            ["base_ingredient_category_id"],
            ["id"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("base_ingredient") as batch_op:
        batch_op.drop_constraint("foreign_ingredient_category_id", type_="foreignkey")
        batch_op.drop_column("base_ingredient_category_id")
    op.drop_table("base_ingredient_category")
    # ### end Alembic commands ###
